version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: restaurant-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - restaurant-network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: restaurant-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/restaurant?schema=public
      NODE_ENV: development
      PORT: 5000
      GOOGLE_CLIENT_EMAIL: ${GOOGLE_CLIENT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
    ports:
      - "5000:5000"
    networks:
      - restaurant-network
    volumes:
      - ./backend:/app
      - /app/node_modules # Evita sobrescribir node_modules del contenedor
      # 1. ENTRYPOINT ejecuta el setup (genera, migra) y termina.
    entrypoint: ["sh", "-c", "npx prisma generate && npx prisma migrate deploy"]
  # 2. COMMAND se ejecuta despu√©s del ENTRYPOINT y mantiene el contenedor vivo (npm run dev)
    command: ["npm", "run", "dev"]
    #command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    #command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run build && npm run start"
    #ommand: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"
    #command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"


    # Backend Node.js

  
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: restaurant-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - restaurant-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge